development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: rightnow_oms_development
  pool: 5
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: rightnow_oms_test
  pool: 5
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock
